import { Platform } from 'react-native';

import { COLLECTIONS } from '@/constants/app';
import type { AppUser } from '@/types';

import { setDocById, updateDocById } from './firestore';

/**
 * Notifications that reach the phone when the app is shut.
 *
 * Everything the app already had went into its own Notification Centre, which
 * only exists while somebody is looking at it. This is the other thing: the
 * lock screen, the shade, the count on the icon.
 *
 * WHY WEB PUSH AND NOT FIREBASE MESSAGING. Both end up at the same place, and
 * FCM would need a key generated by hand in the Firebase console plus a paid
 * plan to send from a Cloud Function. Plain Web Push is the browser standard
 * underneath FCM: the app holds a public key, the browser hands back a
 * subscription, and anything holding the matching private key can push to it.
 * No console, no billing, and the sender can run anywhere — see
 * scripts/send-push.js.
 *
 * WHAT IS SECRET AND WHAT IS NOT. The application server key below is public
 * by design; it is in every copy of the app and is meant to be. The private
 * half never leaves the machine that sends, and is not in this bundle.
 *
 * A subscription is per BROWSER, not per person: the same student on a phone
 * and a laptop is two subscriptions, and both should ring. So they are stored
 * as their own documents keyed by endpoint rather than a single field on the
 * user.
 */

/**
 * The public half of the VAPID pair. Safe to ship — it identifies this app to
 * the push service and can only be used to subscribe, never to send.
 */
const APPLICATION_SERVER_KEY = process.env.EXPO_PUBLIC_VAPID_PUBLIC_KEY ?? '';

export type PushState = 'unsupported' | 'default' | 'granted' | 'denied';

/** What the browser will let us do, before anything is asked of the person. */
export function pushState(): PushState {
  if (Platform.OS !== 'web' || typeof window === 'undefined') return 'unsupported';
  if (!('serviceWorker' in navigator) || !('PushManager' in window)) return 'unsupported';
  if (!('Notification' in window)) return 'unsupported';
  // Without the key nothing can subscribe, and offering the switch would be
  // offering something that cannot work.
  if (!APPLICATION_SERVER_KEY) return 'unsupported';
  return Notification.permission as PushState;
}

/** base64url to the Uint8Array the subscribe call wants. */
function decodeKey(base64: string): Uint8Array {
  const padded = base64.padEnd(base64.length + ((4 - (base64.length % 4)) % 4), '=');
  const raw = window.atob(padded.replace(/-/g, '+').replace(/_/g, '/'));
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i += 1) bytes[i] = raw.charCodeAt(i);
  return bytes;
}

/** The keys, as the push protocol wants them: base64url strings. */
function encodeKey(buffer: ArrayBuffer | null): string {
  if (!buffer) return '';
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return window.btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

/**
 * A stable id for a subscription.
 *
 * The endpoint is a long URL and Firestore ids cannot hold one, so it is
 * hashed. FNV-1a, because this is identity and not security — the same browser
 * must land on the same document so re-subscribing replaces rather than
 * accumulates.
 */
function idFor(endpoint: string): string {
  let hash = 0x811c9dc5;
  for (let i = 0; i < endpoint.length; i += 1) {
    hash ^= endpoint.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return `s${hash.toString(36)}${endpoint.length.toString(36)}`;
}

/**
 * Whether a subscription was made with the key we are about to sign with.
 *
 * `options.applicationServerKey` is the raw key the browser recorded at
 * subscribe time. It is absent on some older engines, and there the honest
 * answer is "cannot tell" — treated as a match rather than forcing a needless
 * resubscribe on browsers that were never the problem.
 */
function sameKey(recorded: ArrayBuffer | null, current: Uint8Array): boolean {
  if (!recorded) return true;
  const seen = new Uint8Array(recorded);
  if (seen.length !== current.length) return false;
  for (let i = 0; i < seen.length; i += 1) {
    if (seen[i] !== current[i]) return false;
  }
  return true;
}

/**
 * Asks permission, subscribes this browser, and records it.
 *
 * Must be called from something the person did — browsers refuse a permission
 * prompt that was not asked for, and Safari discards it silently.
 *
 * Returns the state afterwards so the caller can say what happened, including
 * when the answer was no.
 */
export async function enablePush(user: AppUser): Promise<PushState> {
  if (pushState() === 'unsupported') return 'unsupported';

  const permission = await Notification.requestPermission();
  if (permission !== 'granted') return permission as PushState;

  const registration = await navigator.serviceWorker.ready;

  const serverKey = decodeKey(APPLICATION_SERVER_KEY);

  /**
   * An existing subscription is reused ONLY if it was made with the key we are
   * still signing with.
   *
   * A subscription is bound to the application server key that created it. If
   * that key is ever replaced — and it has to be replaceable, because a leaked
   * one is only fixed by replacing it — the push service starts rejecting every
   * message with a 403 while the browser goes on reporting a perfectly healthy
   * subscription. Nothing surfaces. Notifications simply stop, for everybody,
   * for good, because this function kept handing back the stale subscription
   * and never asked for a new one.
   *
   * So the recorded key is compared against the current one, and a mismatch is
   * unsubscribed before resubscribing. The person sees nothing; the next push
   * arrives as usual.
   */
  const existing = await registration.pushManager.getSubscription();
  const stale =
    existing !== null && !sameKey(existing.options?.applicationServerKey ?? null, serverKey);

  if (existing && stale) {
    await existing.unsubscribe().catch(() => undefined);
  }

  const subscription =
    (!stale && existing) ||
    (await registration.pushManager.subscribe({
      // Without this the push service will accept a message from anybody, and
      // Chrome refuses the subscription outright.
      userVisibleOnly: true,
      applicationServerKey: serverKey as BufferSource,
    }));

  await setDocById(
    COLLECTIONS.pushSubscriptions,
    idFor(subscription.endpoint),
    {
      userId: user.uid,
      userName: user.fullName,
      role: user.role,
      classId: user.classId ?? null,
      branchId: user.branchId ?? null,
      endpoint: subscription.endpoint,
      p256dh: encodeKey(subscription.getKey('p256dh')),
      auth: encodeKey(subscription.getKey('auth')),
      // Which browser this is, so an admin looking at a list of subscriptions
      // can tell one of somebody's devices from another.
      agent: navigator.userAgent.slice(0, 180),
      failures: 0,
    },
    { actorId: user.uid }
  );

  return 'granted';
}

/** Stops this browser receiving, and forgets it. */
export async function disablePush(): Promise<void> {
  if (pushState() === 'unsupported') return;
  const registration = await navigator.serviceWorker.ready;
  const subscription = await registration.pushManager.getSubscription();
  if (!subscription) return;

  const id = idFor(subscription.endpoint);
  await subscription.unsubscribe().catch(() => undefined);
  // Soft-deleted rather than removed, so the sender skips it and a record of
  // the device having existed survives.
  await updateDocById(COLLECTIONS.pushSubscriptions, id, { deleted: true }).catch(
    () => undefined
  );
}

/** True when this browser is already subscribed. */
export async function isSubscribed(): Promise<boolean> {
  if (pushState() !== 'granted') return false;
  const registration = await navigator.serviceWorker.ready;
  return Boolean(await registration.pushManager.getSubscription());
}
